import { invoke } from "@tauri-apps/api/core";
import { listen, type UnlistenFn } from "@tauri-apps/api/event";
import type { Transcript, VideoInfo, ProgressUpdate } from "../types/transcript";

export interface CaptionsResult {
  source: "captions" | "none";
  videoId: string;
  language: string;
  isAutoGenerated: boolean;
  segments: Transcript["segments"];
  text: string;
}

export async function testWorker(): Promise<string> {
  return invoke<string>("test_worker");
}

export async function getVideoInfo(url: string): Promise<VideoInfo> {
  const result = await invoke<{ action?: string; data?: VideoInfo }>(
    "get_video_info",
    { url }
  );
  if (result.data) {
    return result.data;
  }
  throw new Error("Invalid response from worker");
}

export async function getCaptions(
  url: string,
  language?: string
): Promise<CaptionsResult> {
  const result = await invoke<{ action?: string; data?: CaptionsResult }>(
    "get_captions",
    { url, language }
  );
  if (result.data) {
    return result.data;
  }
  throw new Error("Invalid response from worker");
}

export async function transcribe(
  url: string,
  model?: string,
  language?: string,
  jobId?: string
): Promise<void> {
  return invoke<void>("transcribe", { url, model, language, jobId });
}

export async function cancelTranscription(): Promise<void> {
  return invoke<void>("cancel_transcription");
}

export async function getSettings(): Promise<Record<string, unknown>> {
  return invoke<Record<string, unknown>>("get_settings");
}

export async function saveSettings(
  settings: Record<string, unknown>
): Promise<void> {
  return invoke<void>("save_settings", { settings });
}

export async function exportTranscript(
  transcript: Transcript,
  format: "txt" | "srt" | "json"
): Promise<string> {
  return invoke<string>("export_transcript", { transcript, format });
}

export function onProgress(
  callback: (update: ProgressUpdate) => void
): Promise<UnlistenFn> {
  return listen<ProgressUpdate>("transcription-progress", (event) => {
    callback(event.payload);
  });
}

export function onResult(
  callback: (transcript: Transcript) => void
): Promise<UnlistenFn> {
  return listen<Transcript>("transcription-result", (event) => {
    callback(event.payload);
  });
}

export function onError(callback: (message: string) => void): Promise<UnlistenFn> {
  return listen<string>("transcription-error", (event) => {
    callback(event.payload);
  });
}

export function onCancelled(callback: () => void): Promise<UnlistenFn> {
  return listen("transcription-cancelled", () => {
    callback();
  });
}

export interface TranscriptMetadata {
  id: string;
  videoId: string;
  url: string;
  title: string;
  channel?: string;
  duration?: number;
  language?: string;
  source: string;
  createdAt: number;
  updatedAt: number;
  status: string;
  downloadTime?: number;
  transcribeTime?: number;
}

export interface TranscriptData {
  videoId: string;
  title: string;
  channel?: string;
  duration?: number;
  language?: string;
  source: string;
  segments: Transcript["segments"];
  text: string;
}

export async function saveTranscript(
  metadata: TranscriptMetadata,
  data: TranscriptData
): Promise<void> {
  return invoke<void>("save_transcript", { metadata, data });
}

export async function listTranscripts(): Promise<TranscriptMetadata[]> {
  return invoke<TranscriptMetadata[]>("list_transcripts");
}

export async function getTranscriptData(
  transcriptId: string
): Promise<{ metadata: TranscriptMetadata; data: TranscriptData }> {
  const result = await invoke<[TranscriptMetadata, TranscriptData]>(
    "get_transcript_data",
    { transcriptId }
  );
  return { metadata: result[0], data: result[1] };
}

export async function deleteTranscript(transcriptId: string): Promise<void> {
  return invoke<void>("delete_transcript", { transcriptId });
}

export async function searchTranscripts(
  query: string
): Promise<TranscriptMetadata[]> {
  return invoke<TranscriptMetadata[]>("search_transcripts", { query });
}

export async function checkModelDownloaded(model: string): Promise<boolean> {
  return invoke<boolean>("check_model_downloaded", { model });
}
