"""
YouTube Captions Parser
Handles fetching and parsing YouTube captions.
"""

import json
import re
import subprocess
import sys
import urllib.request
import tempfile
import os
from typing import Optional


def get_yt_dlp_cmd():
    """Get the yt-dlp command (executable or module)."""
    import shutil
    yt_dlp_path = shutil.which("yt-dlp")
    if yt_dlp_path:
        return [yt_dlp_path]
    return [sys.executable, "-m", "yt_dlp"]


def fetch_captions(url: str, language: str = "auto") -> dict:
    """
    Fetch captions for a YouTube video.
    
    Returns:
        {
            "source": "captions" | "none",
            "language": str,
            "isAutoGenerated": bool,
            "segments": [{"id": int, "start": float, "end": float, "text": str}]
        }
    """
    yt_dlp_cmd = get_yt_dlp_cmd()
    
    result = subprocess.run(
        yt_dlp_cmd + ["--dump-single-json", "--no-download", url],
        capture_output=True,
        text=True,
        timeout=30,
    )
    
    if result.returncode != 0:
        raise Exception("Failed to fetch video info")
    
    info = json.loads(result.stdout)
    video_id = info.get("id", "")
    subtitles = info.get("subtitles", {})
    auto_captions = info.get("automatic_captions", {})
    
    caption_lang, is_auto = select_caption_language(subtitles, auto_captions, language)
    
    if not caption_lang:
        return {
            "source": "none",
            "videoId": video_id,
            "language": "",
            "isAutoGenerated": False,
            "segments": [],
            "text": "",
        }
    
    actual_lang = caption_lang.replace("auto-", "") if is_auto else caption_lang
    cap_source = auto_captions if is_auto else subtitles
    
    if caption_lang not in cap_source or not cap_source[caption_lang]:
        return {
            "source": "none",
            "videoId": video_id,
            "language": "",
            "isAutoGenerated": False,
            "segments": [],
            "text": "",
        }
    
    formats = cap_source[caption_lang]
    
    caption_url = None
    caption_format = None
    
    for fmt in formats:
        ext = fmt.get("ext", "")
        if ext == "json3":
            caption_url = fmt.get("url")
            caption_format = "json3"
            break
    
    if not caption_url:
        for fmt in formats:
            ext = fmt.get("ext", "")
            if ext == "vtt":
                caption_url = fmt.get("url")
                caption_format = "vtt"
                break
    
    if not caption_url:
        for fmt in formats:
            caption_url = fmt.get("url")
            caption_format = fmt.get("ext", "vtt")
            break
    
    if not caption_url:
        return {
            "source": "none",
            "videoId": video_id,
            "language": "",
            "isAutoGenerated": False,
            "segments": [],
            "text": "",
        }
    
    content = download_caption(caption_url)
    
    if caption_format == "json3":
        segments = parse_json3(content)
    else:
        segments = parse_vtt(content)
    
    segments = clean_segments(segments)
    segments = deduplicate_segments(segments)
    
    for i, seg in enumerate(segments):
        seg["id"] = i
    
    text = "\n\n".join(seg["text"] for seg in segments)
    
    return {
        "source": "captions",
        "videoId": video_id,
        "language": actual_lang,
        "isAutoGenerated": is_auto,
        "segments": segments,
        "text": text,
    }


def select_caption_language(subtitles: dict, auto_captions: dict, preferred_language: str) -> tuple:
    """
    Select the best caption language.
    
    Returns: (caption_key, is_auto_generated)
    """
    if preferred_language and preferred_language != "auto":
        if preferred_language in subtitles:
            return preferred_language, False
        auto_key = f"auto-{preferred_language}"
        if auto_key in auto_captions:
            return auto_key, True
    
    fallback_order = ["en", "zh-Hans", "zh-Hant", "zh", "ja", "ko"]
    
    for lang in fallback_order:
        if lang in subtitles:
            return lang, False
        auto_key = f"auto-{lang}"
        if auto_key in auto_captions:
            return auto_key, True
    
    if subtitles:
        first_lang = next(iter(subtitles))
        return first_lang, False
    
    if auto_captions:
        first_lang = next(iter(auto_captions))
        return f"auto-{first_lang}", True
    
    return None, False


def download_caption(url: str) -> str:
    """Download caption content from URL."""
    try:
        req = urllib.request.Request(
            url,
            headers={"User-Agent": "Mozilla/5.0 (compatible; YouTube Transcript)"}
        )
        with urllib.request.urlopen(req, timeout=15) as response:
            return response.read().decode("utf-8")
    except Exception as e:
        raise Exception(f"Failed to download caption: {e}")


def parse_json3(content: str) -> list:
    """Parse JSON3 caption format."""
    try:
        data = json.loads(content)
        events = data.get("events", [])
        segments = []
        
        for event in events:
            segs = event.get("segs", [])
            if not segs:
                continue
            
            start_ms = event.get("tStartMs", 0)
            dur_ms = event.get("dDurationMs", 0)
            
            text_parts = []
            for seg in segs:
                utf8 = seg.get("utf8", "")
                if utf8 and utf8.strip():
                    text_parts.append(utf8)
            
            if text_parts:
                text = "".join(text_parts).strip()
                text = re.sub(r"<[^>]+>", "", text)
                text = text.replace("\n", " ").strip()
                
                if text:
                    segments.append({
                        "id": len(segments),
                        "start": start_ms / 1000.0,
                        "end": (start_ms + dur_ms) / 1000.0,
                        "text": text,
                    })
        
        return segments
    except Exception:
        return []


def parse_vtt(content: str) -> list:
    """Parse VTT subtitle content into segments."""
    segments = []
    lines = content.split("\n")
    current_start = None
    current_end = None
    current_text = []
    
    for line in lines:
        line = line.strip()
        
        if "-->" in line:
            parts = line.split("-->")
            if len(parts) == 2:
                current_start = parse_vtt_time(parts[0].strip())
                current_end = parse_vtt_time(parts[1].strip())
                current_text = []
        elif line and not line.startswith("WEBVTT") and not line.startswith("Kind:") and not line.startswith("Language:"):
            if current_start is not None:
                clean_text = re.sub(r"<[^>]+>", "", line)
                clean_text = clean_text.replace("\n", " ").strip()
                if clean_text:
                    current_text.append(clean_text)
        
        if current_start is not None and current_text and (not line or line == ""):
            segments.append({
                "id": len(segments),
                "start": current_start,
                "end": current_end or current_start,
                "text": " ".join(current_text),
            })
            current_start = None
            current_end = None
            current_text = []
    
    if current_start is not None and current_text:
        segments.append({
            "id": len(segments),
            "start": current_start,
            "end": current_end or current_start,
            "text": " ".join(current_text),
        })
    
    return segments


def parse_vtt_time(time_str: str) -> float:
    """Parse VTT timestamp to seconds."""
    parts = time_str.replace(",", ".").split(":")
    if len(parts) == 3:
        hours = float(parts[0])
        minutes = float(parts[1])
        seconds = float(parts[2])
        return hours * 3600 + minutes * 60 + seconds
    elif len(parts) == 2:
        minutes = float(parts[0])
        seconds = float(parts[1])
        return minutes * 60 + seconds
    return 0.0


def clean_segments(segments: list) -> list:
    """Clean up segment text."""
    cleaned = []
    for seg in segments:
        text = seg["text"]
        
        text = re.sub(r"<\d{2}:\d{2}:\d{2}\.\d{3}>", "", text)
        text = re.sub(r"<\d{2}:\d{2}\.\d{3}>", "", text)
        
        text = text.replace("&amp;", "&")
        text = text.replace("&lt;", "<")
        text = text.replace("&gt;", ">")
        text = text.replace("&quot;", '"')
        text = text.replace("&#39;", "'")
        text = text.replace("&nbsp;", " ")
        
        text = re.sub(r"\s+", " ", text).strip()
        
        if text:
            cleaned.append({
                "id": seg["id"],
                "start": seg["start"],
                "end": seg["end"],
                "text": text,
            })
    
    return cleaned


def deduplicate_segments(segments: list) -> list:
    """
    Deduplicate segments where current is a prefix of previous.
    Auto-captions often have overlapping text.
    """
    if not segments:
        return segments
    
    deduped = [segments[0]]
    
    for seg in segments[1:]:
        prev_text = deduped[-1]["text"]
        curr_text = seg["text"]
        
        if curr_text == prev_text:
            continue
        
        if prev_text.startswith(curr_text):
            continue
        
        deduped.append(seg)
    
    return deduped
